confirm_os_window_close 0
macos_quit_when_last_window_closed yes
shell zsh -c "tmux new -t main || tmux new -s main"

wheel_scroll_multiplier 1.0

font_family JetBrainsMonoNL Nerd Font Mono
font_size 16
text_composition_strategy legacy
macos_thicken_font 0.1
macos_option_as_alt left

window_padding_width 12
placement_strategy center
hide_window_decorations titlebar-only

clipboard_control write-clipboard write-primary read-clipboard read-primary

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# new OS window running plain zsh (bypasses the tmux shell)
map cmd+shift+n launch --type=os-window zsh --login
