windowrule {
  name = fullscreen_minecraft-rf
  match:class = ^Raspberry Flavoured \d+\.\d+(\.\d+)?$
  float = false
}

windowrule {
  name = prismlauncher_loader
  match:class = ^org\.prismlauncher\.PrismLauncher$
  match:initial_title = Please wait... — Prism Launcher .+
  pseudo = true
  float = true
  no_initial_focus = true
  no_blur = true
  no_dim = true
  no_shadow = true
  decorate = false
  maximize = false
  center = true
}
