windowrule {
  name = windscribe
  match:class = ^Windscribe$
  float = true
  decorate = false
  no_blur = true
  no_dim = true
  no_shadow = true
  monitor = current
  move = monitor_w-window_w-14 40
}

