#!/usr/bin/env zsh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# set mouse follows focus mode (default: off)
# yabai -m config mouse_follows_focus on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow off

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config normal_window_border_color 0x44ffffff
yabai -m config active_window_border_color 0x11000000

