#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse autofocus

# Tell karabiner bindings that yabai is in use
# (after a 5 second delay, hopefully karabiner is ready by then)
(
  sleep 5 && \
  karabiner_cli --set-variables '{"wm": "yabai"}'
) &
