monitor = , preferred, auto, auto
monitor = desc:LG Electronics LG ULTRAWIDE 0x000256D7, 2560x1080@60.0, 440x0, 1.0
monitor = desc:Huawei Technologies Co. Inc. ZQE-CAA 0xC080F622, 3440x1440@165.0, 0x1080, 1.0
