workspace = 1, monitor:desc:Huawei Technologies Co. Inc. ZQE-CAA 0xC080F622, default:true
workspace = 10, monitor:desc:LG Electronics LG ULTRAWIDE 0x000256D7, default:true

exec-once = hyprctl dispatch workspace 1
