#!/bin/zsh

# Attaches tmux session immediately after ssh'ing into a remote
ssht() {
    ssh -t "$@" 'sh -c "
        export TERM=xterm-256color;
        sock=/tmp/ssock.`id -u`;
        rm \$sock 2>/dev/null;
        ln -s $SSH_AUTH_SOCK \$sock;
        export SSH_AUTH_SOCK=\$sock;
        command -v tmux >/dev/null && (tmux -u attach 2>/dev/null || tmux -u new)
    "'
}
