#!/bin/zsh

to-clip() {
    # Copy stdin to clipboard depending on which clipboard tool is available
    # And ultimately fallback to osc52 if nothing is available
    if [[ $commands[pbcopy] ]]; then
        pbcopy
    elif [[ $commands[xclip] ]]; then
        xclip -selection clipboard
    else
        # osc52
        printf "\e]52;c;$(base64)\a"
    fi
}
