#!/bin/bash

# Get current state
CURRENT_MODE=$(gsettings get org.gnome.desktop.interface color-scheme)

TARGET_MODE=""

if [ "$CURRENT_MODE" == "'prefer-dark'" ]; then
    # Switch to LIGHT
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita' # Or your light theme

    TARGET_MODE="light"
else
    # Switch to DARK
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' # Or your dark theme

    TARGET_MODE="dark"
fi

# just in case nvr is currently in a mise virtualenv
if command -v mise &&>/dev/null; then
    eval "$(mise activate bash)"
fi

# Run nvr to update nvim's current theme
if command -v nvr &&>/dev/null; then
  for server in $(ls /run/user/$(id -u)/nvim.*.0 2>/dev/null) /tmp/nvimsocket; do
      nvr --servername "$server" -c "set background=$TARGET_MODE" &
  done
fi
