# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.dotfiles/omarchy/hypr/envs.conf
source = ~/.dotfiles/omarchy/hypr/autostart.conf
source = ~/.dotfiles/omarchy/hypr/bindings.conf
source = ~/.dotfiles/omarchy/hypr/monitors.conf
source = ~/.dotfiles/omarchy/hypr/input.conf
source = ~/.dotfiles/omarchy/hypr/looknfeel.conf
source = ~/.dotfiles/omarchy/hypr/rules.conf

