# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf

windowrule {
  name = no_maximize
  match:class = .*
  suppress_event = maximize
}

# Tag all windows for default opacity (apps can override with -default-opacity tag)
windowrule {
  name = opacity_tag
  match:class = .*
  tag = +default-opacity
}

# Fix some dragging issues with XWayland
windowrule {
  name = xwayland_fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
  no_focus = on
}

# App-specific tweaks (may remove default-opacity tag)
source = ~/.local/share/omarchy/default/hypr/apps.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
windowrule {
  name = fullscreen_minecraft-rf
  match:class = ^Raspberry Flavoured \d+\.\d+(\.\d+)?$
  float = false
  workspace = 9
}

windowrule {
  name = prismlauncher_loader
  match:class = ^org\.prismlauncher\.PrismLauncher$
  match:initial_title = Please wait... — Prism Launcher .+
  pseudo = true
  float = true
  no_initial_focus = true
  no_blur = true
  no_dim = true
  no_shadow = true
  decorate = false
  maximize = false
  center = true
}

windowrule {
  name = windscribe
  match:class = ^Windscribe$
  float = true
  decorate = false
  no_blur = true
  no_dim = true
  no_shadow = true
  monitor = current
  move = monitor_w-window_w-14 40
}

# Apply default opacity after apps have had a chance to opt out
windowrule {
  name = opacity
  match:tag = default-opacity
  opacity = 1 0.9
}

