#!/bin/zsh

# force 256-color mode when inside containers
if grep -sq "docker\|lxc" /proc/1/cgroup; then
  export TERM=xterm-256color
fi

# ls aliases
alias ls="ls --color=auto"
alias ll="ls -lh"
alias la="ls -a"
alias lla="ll -a"

# color aliases
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ip="ip --color=auto"
alias dmesg="dmesg --color=auto"

# eza
if command -v eza &>/dev/null; then
    alias ls=eza
    alias lt='ll --tree'
fi

# bat
if command -v bat &>/dev/null; then
    export BAT_STYLE="snip"
    export BAT_THEME="base16"
    export BAT_THEME_DARK="base16"
    export BAT_THEME_LIGHT="base16"
    alias cat=bat
fi

# zoxide
if command -v zoxide &>/dev/null; then
    eval "$(zoxide init zsh)"
fi

# neovim
if command -v nvim &>/dev/null; then
    export EDITOR=nvim
elif command -v vim &>/dev/null; then
    export EDITOR=vim
fi

# keybindings
source "$ZDOTDIR/keybindings"

# less
export LESS=" \
    --quit-if-one-screen \
    --ignore-case \
    --status-column \
    --LONG-PROMPT \
    --RAW-CONTROL-CHARS \
    --HILITE-UNREAD \
    --tabs=4 \
    --no-init \
    --window=-4 \
"
# a couple of keybindings and color config for less
# requires a fairly recent version of less
export LESSKEYIN="$HOME/.dotfiles/.lesskey"

# zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [[ ! -d "$ZINIT_HOME" ]]; then
    ZINIT_HOME="$(dirname "$ZINIT_HOME")" \
    NO_EMOJI=1 \
    NO_INPUT=1 \
    NO_TUTORIAL=1 \
    NO_ANNEXES=1 \
    NO_EDIT=1 \
    sh -c "$(curl -fsSL https://git.io/zinit-install)"
fi

source "$ZINIT_HOME/zinit.zsh"

# powerlevel10k theme
zinit ice depth=1
zinit light romkatv/powerlevel10k

# fast syntax highlighting
zinit ice wait=!0 lucid depth=1
zinit light zdharma-continuum/fast-syntax-highlighting

# fish-like abbreviations, aliases that auto-expand when pressing space
init_abbr() {
    ABBR_USER_ABBREVIATIONS_FILE="$ZDOTDIR/abbreviations"
    ABBR_AUTOLOAD=0
    ABBR_DEFAULT_BINDINGS=0
    bindkey " " abbr-expand-and-insert # space to expand abbr
    bindkey "^ " magic-space # ctrl+space to insert space without expanding abbr
    bindkey -M isearch " " magic-space # normal space is normal in incremental search
    bindkey -M isearch "^ " abbr-expand-and-insert # ctrl+space expands abbr in isearch

    # Allows abbreviation to be expanded on enter if they're the only command to execute
    _expand_abbr_and_accept() {
        emulate -LR zsh

        # make sure the rbuffer doesn't start with a space
        if [[ ! "$RBUFFER" || "$RBUFFER" =~ ^[[:space:]].+ ]]; then
            abbr-expand-and-accept
        else
            zle accept-line
        fi
    }
    zle -N _expand_abbr_and_accept
    bindkey "^M" _expand_abbr_and_accept
}
zinit ice wait=0 lucid depth=1 atinit=init_abbr
zinit light olets/zsh-abbr

# fish like substring search
init_substring_search() {
    HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=underline
    HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=fg=8,underline
    HISTORY_SUBSTRING_SEARCH_FUZZY=1
    bindkey '^[[A' history-substring-search-up # up
    bindkey '^[OA' history-substring-search-up
    bindkey '^[[B' history-substring-search-down # down
    bindkey '^[OB' history-substring-search-down
}
zinit ice wait=0 lucid depth=1 atinit=init_substring_search
zinit light zsh-users/zsh-history-substring-search

# forgit
zinit ice wait=0 lucid depth=1
zinit light wfxr/forgit

# fzf
if command -v fzf &>/dev/null; then
    reconfigure_fzf_preview() {
        # configure the preview window

        local fzf_default_ops_base="
            --ansi
            --cycle
            --reverse
            --info=inline
            --height=30%
            --border=rounded
            --preview='preview {}'
            --pointer=·
            --marker=→
            --color=fg:246,fg+:4,bg+:0,gutter:16,pointer:14,info:2,header:11,hl:7,hl+:7
            --bind='ctrl-space:toggle-down'
            --bind='ctrl-z:toggle-preview'
            --bind='ctrl-o:execute-silent(code {} &)'
            --bind='ctrl-p:execute-silent(code {} &)+abort'
            --bind='ctrl-u:preview-up+preview-up+preview-up+preview-up+preview-up'
            --bind='ctrl-d:preview-down+preview-down+preview-down+preview-down+preview-down'
            --bind='ctrl-r:toggle-all'
            --bind='ctrl-s:toggle-sort'
            --bind='ctrl-w:toggle-preview-wrap'
            --bind='home:first'
            --bind='end:last'
        "
        local fzf_ctrl_t_ops_base="--no-height --no-border"
        local fzf_alt_c_ops_base="--no-height --no-border"

        # sets fzf preview position and status (no/hidden) depending on terminal size
        local hide_threshold_columns=74
        local hide_threshold_lines=36
        local lines_factor=2.3 # assume that a cell is n times a tall as it wide

        local preview_window="default"
        local nohidden=",nohidden"

        if ((COLUMNS > LINES * lines_factor)); then   # screen is wider than it is tall
            preview_window="right,50%,border-left"

            # force hide the preview window if the screen is not wide enough
            if ((COLUMNS < hide_threshold_columns)); then
                nohidden=",hidden"
            fi
        else # screen is taller than it is wide
            preview_window="bottom,50%,border-top"

            # force hide the preview window if the screen is not tall enough
            if ((LINES < hide_threshold_lines)); then
                nohidden=",hidden"
            fi
        fi

        export FZF_DEFAULT_OPTS="$fzf_default_ops_base --preview-window=${preview_window},hidden"
        export FZF_CTRL_T_OPTS="$fzf_ctrl_t_ops_base --preview-window=${preview_window}${nohidden}"
        export FZF_ALT_C_OPTS="$fzf_alt_c_ops_base --preview-window=${preview_window}${nohidden}"
    }

    export FZF_DEFAULT_COMMAND="fd --type f --type l --color=never --no-ignore-vcs --hidden"
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd --type d --color=never --no-ignore-vcs --hidden"

    # reconfigure preview options whenever the terminal resizes
    trap reconfigure_fzf_preview SIGWINCH

    # set initial fzf preview window options
    reconfigure_fzf_preview

    eval "$(fzf --zsh)"
fi

# Enable automatic activation of virtualenvs
if command -v pyenv &>/dev/null; then
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
